version: '3.8'
services:
  rasa:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5005:5005"
      - "5055:5055"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
    volumes:
      - ./:/app
